---
- name: "include var"
  include_vars: ../defaults/main.yml

- name: "Download the release"
  command: "wget -O telegraf.deb {{ binary_url }}"
  args:
    chdir: "/tmp"

- name: "Install the agent"
  command: "dpkg -i telegraf.deb"
  args:
    chdir: "/tmp"